In [ ]:
from sklearn import datasets
import pandas as pd

In [ ]:
# load iris dataset and extracting target feature from it
iris = datasets.load_iris()
data = iris.data
target = iris.target

In [ ]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [ ]:
# creating dataframe of iris dataset
dataset = pd.DataFrame(data , columns=iris.feature_names)

In [ ]:
# Adding target variable into dataset
dataset['target'] = target

In [ ]:

dataset

     sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
0                  5.1               3.5  ...               0.2       0
1                  4.9               3.0  ...               0.2       0
2                  4.7               3.2  ...               0.2       0
3                  4.6               3.1  ...               0.2       0
4                  5.0               3.6  ...               0.2       0
..                 ...               ...  ...               ...     ...
145                6.7               3.0  ...               2.3       2
146                6.3               2.5  ...               1.9       2
147                6.5               3.0  ...               2.0       2
148                6.2               3.4  ...               2.3       2
149                5.9               3.0  ...               1.8       2

[150 rows x 5 columns]

In [ ]:
dataset[:2] # testing

   sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
0                5.1               3.5  ...               0.2       0
1                4.9               3.0  ...               0.2       0

[2 rows x 5 columns]

In [ ]:
dataset[2:8] # training data

   sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
2                4.7               3.2  ...               0.2       0
3                4.6               3.1  ...               0.2       0
4                5.0               3.6  ...               0.2       0
5                5.4               3.9  ...               0.4       0
6                4.6               3.4  ...               0.3       0
7                5.0               3.4  ...               0.2       0

[6 rows x 5 columns]

In [ ]:
# Mathematical calculation of knn
# sqrt[(4.7 - 5.1)^2 + (3.2-3.5)^2 + (1.3-1.4)^2 + (0.2-0.2)^2]  ==== 1.2 >>>> 1
# sqrt[(4.6 - 5.1)^2 + (3.11-3.5)^2 + (1.5-1.4)^2 + (0.2-0.2)^2]  ==== 1.6 >>>>> 2
# sqrt[(5.0 - 5.1)^2 + (3.6-3.5)^2 + (1.4-1.4)^2 + (0.2-0.2)^2]  ==== 1.4 >>>> 0
# sqrt[(4.7 - 5.1)^2 + (3.2-3.5)^2 + (1.3-1.4)^2 + (0.2-0.2)^2]  ==== 1.7>>>> 0
# sqrt[(4.6 - 5.1)^2 + (3.11-3.5)^2 + (1.5-1.4)^2 + (0.2-0.2)^2]  ==== 1.2 >>>>> 03
# sqrt[(5.0 - 5.1)^2 + (3.6-3.5)^2 + (1.4-1.4)^2 + (0.2-0.2)^2]  ==== 1.1 >>>> 0    


#neighbours = 4  
#selected_distance = 1.1 , 1.2 ,1.2 ,1.4                                                                                          
#labels =  1 , 1, 2 , 0  
#max_occured_label = 1
# assign max_occured_label as class of testing data point

In [ ]:
#categorical target class label
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [ ]:
# converting numeric values into categorical feature
target_names = []
for i in range(0,len(dataset)):
  if dataset['target'][i] == 0:    
    target_names.append('setosa')         
  elif dataset['target'][i] == 1:
    target_names.append('versicolor')
  elif dataset['target'][i] == 2:
    target_names.append('virgnica')

In [ ]:
dataset['labels'] = target_names
dataset.drop(['target'] , axis='columns' , inplace=True)
dataset

     sepal length (cm)  sepal width (cm)  ...  petal width (cm)    labels
0                  5.1               3.5  ...               0.2    setosa
1                  4.9               3.0  ...               0.2    setosa
2                  4.7               3.2  ...               0.2    setosa
3                  4.6               3.1  ...               0.2    setosa
4                  5.0               3.6  ...               0.2    setosa
..                 ...               ...  ...               ...       ...
145                6.7               3.0  ...               2.3  virgnica
146                6.3               2.5  ...               1.9  virgnica
147                6.5               3.0  ...               2.0  virgnica
148                6.2               3.4  ...               2.3  virgnica
149                5.9               3.0  ...               1.8  virgnica

[150 rows x 5 columns]

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   labels             150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [ ]:
import numpy as np
np.unique(dataset['labels'])

array(['setosa', 'versicolor', 'virgnica'], dtype=object)

In [ ]:
# Machine Learning model doesn't understand string values so we have to convert into numeric values
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
le_target = encoder.fit_transform(dataset['labels'])
print(le_target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]

In [ ]:
#Removing labels columns from dataset
dataset.drop(['labels'] , axis = 'columns' , inplace=True)

In [ ]:
dataset

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [ ]:
le_target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(dataset , le_target , test_size = 0.2 , random_state =3)

In [ ]:
print(len(x_train))
print(len(x_test))

120
30

In [ ]:
#import KNN model 
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
classifier = KNeighborsClassifier(n_neighbors = 3)
classifier.fit(x_train , y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [ ]:
prediction = classifier.predict(x_test)

In [ ]:
# Accuracy score is performance matrics for this project
from sklearn.metrics import accuracy_score
print(accuracy_score(prediction , y_test))

0.9666666666666667